# Generated by Django 4.1.6 on 2023-02-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BundleProducts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("brand", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("asin", models.CharField(max_length=100)),
                ("modelNumber", models.IntegerField()),
                ("productURL", models.CharField(max_length=300)),
                ("spec", models.TextField()),
                ("technicalDetails", models.TextField(max_length=300)),
                ("about", models.CharField(max_length=300)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customerName", models.CharField(max_length=300)),
                ("textContent", models.TextField()),
                ("reviewDate", models.DateField()),
                (
                    "productID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.products"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("profilePicURL", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sentiment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("postiveRate", models.IntegerField()),
                ("negativeRate", models.IntegerField()),
                ("nuetralRate", models.IntegerField()),
                ("overallSentiment", models.CharField(max_length=100)),
                (
                    "reviewID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.reviews"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="sellerID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
        migrations.CreateModel(
            name="ProductBundles",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bundleProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.bundleproducts",
                    ),
                ),
                (
                    "productID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.products"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("stockCode", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("unitPrice", models.FloatField()),
                ("date", models.DateField()),
                ("customerID", models.CharField(max_length=300)),
                (
                    "sellerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bundleproducts",
            name="sellerID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
