# Generated by Django 4.1.6 on 2023-02-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_sentiment_negativerate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sentiment",
            old_name="nuetralRate",
            new_name="neutralRate",
        ),
        migrations.RenameField(
            model_name="sentiment",
            old_name="postiveRate",
            new_name="positiveRate",
        ),
    ]
