# Generated by Django 4.1.6 on 2023-02-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_nuetralrate_sentiment_neutralrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="name",
            field=models.CharField(default="food", max_length=300),
            preserve_default=False,
        ),
    ]
