# Generated by Django 4.1.6 on 2023-02-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_products_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="about",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="products",
            name="technicalDetails",
            field=models.TextField(),
        ),
    ]
