# Generated by Django 4.1.6 on 2023-02-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_products_about_alter_products_technicaldetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='description',
            new_name='productID',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='stockCode',
        ),
    ]
