# Generated by Django 4.1.6 on 2023-02-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_description_orders_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products'),
        ),
    ]
