# Generated by Django 4.1.6 on 2023-02-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_orders_productid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='country',
            new_name='orderID',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customerID',
        ),
    ]
